services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}
    restart: always
    hostname: "${GITLAB_HOST}"
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SHELL_SSH_PORT:-8229}
        puma['worker_processes'] = 2
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        prometheus['enable'] = false
        postgresql['shared_buffers'] = '256MB'
    ports:
      - "${GITLAB_PORT:-80}:80"
      - "${GITLAB_HTTPS_PORT:-443}:443"
      - "${GITLAB_SSH_PORT:-2222}:22"
    volumes:
      - ./etc/gitlab/config:/etc/gitlab
      - ${GITLAB_LOGS_PATH}:/var/log/gitlab
      - ${GITLAB_DATA_PATH}:/var/opt/gitlab
    shm_size: "256m"
