services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}
    restart: always
    hostname: "${GITLAB_HOST}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1:${APP_PORT:-8281}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${SHELL_PORT:-8229}
        puma['worker_processes'] = 2
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        prometheus['enable'] = false
        postgresql['shared_buffers'] = '256MB'
    ports:
      - "${GITLAB_PORT:-80}:80"
      - "${GITLAB_HTTPS_PORT:-443}:443"
      - "${GITLAB_SSH_PORT:-2222}:22"
    volumes:
      - ./etc/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    shm_size: "256m"
