services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}
    restart: always
    hostname: "${GITLAB_HOST}"
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        nginx['enable'] = ${GITLAB_NGINX_ENABLE:-true}
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SHELL_SSH_PORT:-8229}
        gitlab_rails['force_ssl'] = ${GITLAB_FORCE_SSL:-false}
        gitlab_rails['gitlab_https'] = ${GITLAB_HTTPS:-false}
        
        puma['worker_processes'] = 2
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        prometheus['enable'] = false
        postgresql['shared_buffers'] = '256MB'
        
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${GITLAB_SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${GITLAB_SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${GITLAB_SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${GITLAB_SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${GITLAB_SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${GITLAB_SMTP_AUTHENTICATION}"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_display_name'] = "${GITLAB_EMAIL_DISPLAY_NAME}"
        gitlab_rails['gitlab_email_from'] = "${GITLAB_EMAIL_FROM}"
        gitlab_rails['gitlab_email_reply_to'] = "${GITLAB_EMAIL_REPLY_TO}"
        gitlab_rails['incoming_email_enabled'] = ${GITLAB_INCOMING_EMAIL_ENABLED:-false}
    ports:
      - "${GITLAB_PORT:-80}:80"
      - "${GITLAB_HTTPS_PORT:-443}:443"
      - "${GITLAB_SSH_PORT:-2222}:22"
    volumes:
      - ./etc/gitlab/config:/etc/gitlab
      - ${GITLAB_LOGS_PATH}:/var/log/gitlab
      - ${GITLAB_DATA_PATH}:/var/opt/gitlab
    shm_size: "256m"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '2GB'
        reservations:
          cpus: '1'
          memory: '1GB'
